export const TEMPLATES = {
  aula_filas: {
    name: 'Aula (filas)',
    cols: 6, rows: 4,
    zones: [
      { id: 'f1i1', label: 'Fila 1-Izq1', x: 0, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f1i2', label: 'Fila 1-Izq2', x: 1, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f1c1', label: 'Fila 1-Cen1', x: 2, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f1c2', label: 'Fila 1-Cen2', x: 3, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f1d1', label: 'Fila 1-Der1', x: 4, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f1d2', label: 'Fila 1-Der2', x: 5, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'f2i1', label: 'Fila 2-Izq1', x: 0, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f2i2', label: 'Fila 2-Izq2', x: 1, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f2c1', label: 'Fila 2-Cen1', x: 2, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f2c2', label: 'Fila 2-Cen2', x: 3, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f2d1', label: 'Fila 2-Der1', x: 4, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f2d2', label: 'Fila 2-Der2', x: 5, y: 1, w: 1, h: 1, color: '#fef3c7' },
      { id: 'f3i1', label: 'Fila 3-Izq1', x: 0, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f3i2', label: 'Fila 3-Izq2', x: 1, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f3c1', label: 'Fila 3-Cen1', x: 2, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f3c2', label: 'Fila 3-Cen2', x: 3, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f3d1', label: 'Fila 3-Der1', x: 4, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f3d2', label: 'Fila 3-Der2', x: 5, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'f4i1', label: 'Fila 4-Izq1', x: 0, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'f4i2', label: 'Fila 4-Izq2', x: 1, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'f4c1', label: 'Fila 4-Cen1', x: 2, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'f4c2', label: 'Fila 4-Cen2', x: 3, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'f4d1', label: 'Fila 4-Der1', x: 4, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'f4d2', label: 'Fila 4-Der2', x: 5, y: 3, w: 1, h: 1, color: '#fce7f3' },
    ]
  },
  centro_escolar: {
    name: 'Centro Escolar',
    cols: 8, rows: 6,
    zones: [
      { id: 'entrada', label: 'Entrada', x: 0, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'secretaria', label: 'Secretaría', x: 1, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'direccion', label: 'Dirección', x: 2, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'salaprofe', label: 'Sala Prof', x: 3, y: 0, w: 1, h: 1, color: '#f3e8ff' },
      { id: 'aula101', label: 'Aula 101', x: 4, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula102', label: 'Aula 102', x: 5, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula103', label: 'Aula 103', x: 6, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'banos', label: 'Baños', x: 7, y: 0, w: 1, h: 1, color: '#fce7f3' },
      { id: 'pasilloppal', label: 'Pasillo Ppal', x: 0, y: 1, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'aula104', label: 'Aula 104', x: 2, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula105', label: 'Aula 105', x: 3, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula106', label: 'Aula 106', x: 4, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'biblioteca', label: 'Biblioteca', x: 5, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'informatica', label: 'Informática', x: 6, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'laboratorio', label: 'Laboratorio', x: 7, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'comedor', label: 'Comedor', x: 0, y: 2, w: 2, h: 1, color: '#fef3c7' },
      { id: 'cocina', label: 'Cocina', x: 2, y: 2, w: 1, h: 1, color: '#fef3c7' },
      { id: 'patiocub', label: 'Patio Cubierto', x: 3, y: 2, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'canchafut', label: 'Cancha Fútbol', x: 4, y: 2, w: 2, h: 2, color: '#dcfce7' },
      { id: 'gradas', label: 'Gradas', x: 6, y: 2, w: 1, h: 1, color: '#fce7f3' },
      { id: 'taller', label: 'Taller', x: 7, y: 2, w: 1, h: 1, color: '#fff3e0' },
      { id: 'huerto', label: 'Huerto', x: 0, y: 3, w: 2, h: 1, color: '#dcfce7' },
      { id: 'arboles', label: 'Árboles', x: 2, y: 3, w: 1, h: 1, color: '#dcfce7' },
      { id: 'bancos', label: 'Bancos', x: 3, y: 3, w: 1, h: 1, color: '#fef3c7' },
      { id: 'porche', label: 'Porche', x: 6, y: 3, w: 1, h: 1, color: '#fef3c7' },
      { id: 'musica', label: 'Música', x: 7, y: 3, w: 1, h: 1, color: '#fff3e0' },
      { id: 'fuente', label: 'Fuente', x: 0, y: 4, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'pasilloA', label: 'Pasillo A', x: 1, y: 4, w: 1, h: 1, color: '#f3e8ff' },
      { id: 'sombra', label: 'Sombra', x: 2, y: 4, w: 1, h: 1, color: '#fce7f3' },
      { id: 'esquina', label: 'Esquina', x: 3, y: 4, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'canchabas', label: 'Cancha Baloncesto', x: 4, y: 4, w: 2, h: 1, color: '#dcfce7' },
      { id: 'escaleras', label: 'Escaleras', x: 6, y: 4, w: 1, h: 1, color: '#f3e8ff' },
      { id: 'aparca', label: 'Aparcamiento', x: 7, y: 4, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'pasilloB', label: 'Pasillo B', x: 1, y: 5, w: 1, h: 1, color: '#f3e8ff' },
      { id: 'rincon', label: 'Rincón Tranquilo', x: 2, y: 5, w: 1, h: 1, color: '#fce7f3' },
      { id: 'fuertetras', label: 'Puerta Trasera', x: 3, y: 5, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'banco', label: 'Banco Aislado', x: 4, y: 5, w: 1, h: 1, color: '#fef3c7' },
      { id: 'esquinatras', label: 'Esquina Trasera', x: 5, y: 5, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'patiointer', label: 'Patio Interior', x: 6, y: 5, w: 1, h: 1, color: '#dcfce7' },
      { id: 'almacen', label: 'Almacén', x: 7, y: 5, w: 1, h: 1, color: '#e0f2fe' },
    ]
  },
  aula_grupos: {
    name: 'Aula (grupos)', cols: 4, rows: 4,
    zones: Array.from({length:8}, (_, i) => ({
      id: `group${i+1}`, label: `Grupo ${i+1}`,
      x: (i%4), y: Math.floor(i/4)*2, w: 1, h: 2,
      color: ['#e0f2fe','#dcfce7','#fef3c7','#fce7f3','#f3e8ff','#ffe4e6','#dcfce7','#fff3e0'][i]
    }))
  },
  aula_u: {
    name: 'Aula (U)', cols: 5, rows: 3,
    zones: [
      { id: 'u1', label: 'U-Izq1', x: 0, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'u2', label: 'U-Izq2', x: 0, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'u3', label: 'U-Izq3', x: 0, y: 2, w: 1, h: 1, color: '#fef3c7' },
      { id: 'u4', label: 'U-Frente1', x: 1, y: 2, w: 1, h: 1, color: '#fce7f3' },
      { id: 'u5', label: 'U-Frente2', x: 2, y: 2, w: 1, h: 1, color: '#f3e8ff' },
      { id: 'u6', label: 'U-Frente3', x: 3, y: 2, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'u7', label: 'U-Der3', x: 4, y: 2, w: 1, h: 1, color: '#fef3c7' },
      { id: 'u8', label: 'U-Der2', x: 4, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'u9', label: 'U-Der1', x: 4, y: 0, w: 1, h: 1, color: '#e0f2fe' },
    ]
  },
  pasillos: {
    name: 'Pasillos', cols: 5, rows: 1,
    zones: [
      { id: 'hall1', label: 'Pasillo Norte', x: 0, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'hall2', label: 'Intersección', x: 1, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'hall3', label: 'Pasillo Central', x: 2, y: 0, w: 1, h: 1, color: '#dcfce7' },
      { id: 'hall4', label: 'Intersección Sur', x: 3, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'hall5', label: 'Pasillo Sur', x: 4, y: 0, w: 1, h: 1, color: '#e0f2fe' },
    ]
  },
  instituto: {
    name: 'Instituto', cols: 8, rows: 6,
    zones: [
      { id: 'entrada', label: 'Entrada', x: 0, y: 0, w: 2, h: 1, color: '#e0f2fe' },
      { id: 'secretaria', label: 'Secretaría', x: 2, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'direccion', label: 'Dirección', x: 3, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'jefatura', label: 'Jefatura Est.', x: 4, y: 0, w: 1, h: 1, color: '#fef3c7' },
      { id: 'depart1', label: 'Departamentos', x: 5, y: 0, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'salaactos', label: 'Salón Actos', x: 7, y: 0, w: 1, h: 2, color: '#ffe4e6' },
      { id: 'pasillo1', label: 'Pasillo Ppal', x: 0, y: 1, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'aula101', label: 'Aula 101', x: 2, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula102', label: 'Aula 102', x: 3, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula103', label: 'Aula 103', x: 4, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula104', label: 'Aula 104', x: 5, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula105', label: 'Aula 105', x: 6, y: 1, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'informatica', label: 'Informática', x: 2, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'laboratorio', label: 'Laboratorio', x: 3, y: 2, w: 1, h: 1, color: '#dcfce7' },
      { id: 'aula106', label: 'Aula 106', x: 4, y: 2, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula107', label: 'Aula 107', x: 5, y: 2, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula108', label: 'Aula 108', x: 6, y: 2, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'pasillo2', label: 'Pasillo Trasero', x: 0, y: 2, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'biblioteca', label: 'Biblioteca', x: 0, y: 3, w: 2, h: 2, color: '#dcfce7' },
      { id: 'aula109', label: 'Aula 109', x: 2, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula110', label: 'Aula 110', x: 3, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'gimnasio', label: 'Gimnasio', x: 4, y: 3, w: 2, h: 2, color: '#fff3e0' },
      { id: 'vestuarios', label: 'Vestuarios', x: 6, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'alamacen2', label: 'Almacén', x: 7, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula111', label: 'Aula 111', x: 2, y: 4, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'aula112', label: 'Aula 112', x: 3, y: 4, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'canchafut', label: 'Cancha Fútbol', x: 4, y: 5, w: 2, h: 1, color: '#dcfce7' },
      { id: 'canchabas', label: 'Cancha Baloncesto', x: 6, y: 5, w: 2, h: 1, color: '#dcfce7' },
      { id: 'patio', label: 'Patio', x: 0, y: 5, w: 2, h: 1, color: '#fef3c7' },
      { id: 'comedor', label: 'Comedor', x: 2, y: 5, w: 2, h: 1, color: '#fef3c7' },
      { id: 'banos', label: 'Baños', x: 6, y: 4, w: 1, h: 1, color: '#fce7f3' },
      { id: 'escaleras', label: 'Escaleras', x: 7, y: 4, w: 1, h: 2, color: '#f3e8ff' },
    ]
  },
  polideportivo: {
    name: 'Polideportivo', cols: 6, rows: 4,
    zones: [
      { id: 'entradaP', label: 'Acceso', x: 0, y: 0, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'gradas', label: 'Gradas', x: 0, y: 1, w: 1, h: 2, color: '#f3e8ff' },
      { id: 'pistaCent', label: 'Pista Central', x: 1, y: 0, w: 3, h: 3, color: '#dcfce7' },
      { id: 'pistaLat', label: 'Pista Lateral', x: 4, y: 0, w: 2, h: 2, color: '#dcfce7' },
      { id: 'vestHom', label: 'Vestuario H', x: 4, y: 2, w: 1, h: 1, color: '#fce7f3' },
      { id: 'vestMuj', label: 'Vestuario M', x: 5, y: 2, w: 1, h: 1, color: '#fce7f3' },
      { id: 'alamacenP', label: 'Almacén Mat.', x: 0, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'tribuna', label: 'Tribuna', x: 1, y: 3, w: 2, h: 1, color: '#fff3e0' },
      { id: 'banosP', label: 'Baños', x: 3, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'enfermeria', label: 'Enfermería', x: 4, y: 3, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'despachoP', label: 'Despacho', x: 5, y: 3, w: 1, h: 1, color: '#fef3c7' },
    ]
  },
  comedor: {
    name: 'Comedor', cols: 8, rows: 4,
    zones: [
      { id: 'barra', label: 'Barra', x: 0, y: 0, w: 2, h: 1, color: '#fef3c7' },
      { id: 'cocina', label: 'Cocina', x: 0, y: 1, w: 2, h: 2, color: '#fff3e0' },
      { id: 'almacenC', label: 'Almacén', x: 0, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'mesa1', label: 'Mesa 1-2', x: 2, y: 0, w: 2, h: 1, color: '#e0f2fe' },
      { id: 'mesa2', label: 'Mesa 3-4', x: 4, y: 0, w: 2, h: 1, color: '#e0f2fe' },
      { id: 'mesa3', label: 'Mesa 5-6', x: 6, y: 0, w: 2, h: 1, color: '#e0f2fe' },
      { id: 'mesa4', label: 'Mesa 7-8', x: 2, y: 1, w: 2, h: 1, color: '#dcfce7' },
      { id: 'mesa5', label: 'Mesa 9-10', x: 4, y: 1, w: 2, h: 1, color: '#dcfce7' },
      { id: 'mesa6', label: 'Mesa 11-12', x: 6, y: 1, w: 2, h: 1, color: '#dcfce7' },
      { id: 'mesa7', label: 'Mesa 13-14', x: 2, y: 2, w: 2, h: 1, color: '#fce7f3' },
      { id: 'mesa8', label: 'Mesa 15-16', x: 4, y: 2, w: 2, h: 1, color: '#fce7f3' },
      { id: 'mesa9', label: 'Mesa 17-18', x: 6, y: 2, w: 2, h: 1, color: '#fce7f3' },
      { id: 'terraza', label: 'Terraza', x: 2, y: 3, w: 3, h: 1, color: '#fef3c7' },
      { id: 'banosC', label: 'Baños', x: 5, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'salidaC', label: 'Salida', x: 6, y: 3, w: 2, h: 1, color: '#e0f2fe' },
    ]
  },
  patio: {
    name: 'Patio', cols: 6, rows: 4,
    zones: [
      { id: 'canchafut', label: 'Cancha Fútbol', x: 0, y: 0, w: 2, h: 2, color: '#dcfce7' },
      { id: 'canchabas', label: 'Cancha Baloncesto', x: 2, y: 0, w: 2, h: 2, color: '#dcfce7' },
      { id: 'gradas', label: 'Gradas', x: 4, y: 0, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'zonaarbol', label: 'Zona Árboles', x: 4, y: 1, w: 1, h: 1, color: '#dcfce7' },
      { id: 'banco', label: 'Bancos', x: 5, y: 1, w: 1, h: 1, color: '#fce7f3' },
      { id: 'columpios', label: 'Columpios', x: 0, y: 2, w: 1, h: 1, color: '#fef3c7' },
      { id: 'arenero', label: 'Arenero', x: 1, y: 2, w: 1, h: 1, color: '#fef3c7' },
      { id: 'porche', label: 'Porche', x: 2, y: 2, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'fuente', label: 'Fuente', x: 4, y: 2, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'esquina', label: 'Esquina', x: 5, y: 2, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'pasillo', label: 'Pasillo', x: 0, y: 3, w: 2, h: 1, color: '#f3e8ff' },
      { id: 'rincon', label: 'Rincón Tranquilo', x: 2, y: 3, w: 1, h: 1, color: '#fce7f3' },
      { id: 'entrada', label: 'Entrada', x: 3, y: 3, w: 1, h: 1, color: '#e0f2fe' },
      { id: 'esquinatras', label: 'Esquina Trasera', x: 4, y: 3, w: 1, h: 1, color: '#ffe4e6' },
      { id: 'almacen', label: 'Almacén', x: 5, y: 3, w: 1, h: 1, color: '#e0f2fe' },
    ]
  },
}